### ISSUE TITLE
Issue with selective_scan_cuda

### ISSUE THREAD

**Issue by MariosPapadopoulos** [hustvl/Vim#28]
Hi,

I cannot properly select selective_scan_cuda:
How can the error about the unresolved symbol be solved?

Traceback (most recent call last):
  File "/rds/general/user/kp4718/home/code/Vim/vim/main.py", line 28, in <module>
    import models_mamba
  File "/rds/general/user/kp4718/home/code/Vim/vim/models_mamba.py", line 21, in <module>
    from mamba_ssm.modules.mamba_simple import Mamba
  File "/rds/general/user/kp4718/home/anaconda3/envs/mambaenv/lib/python3.10/site-packages/mamba_ssm/__init__.py", line 3, in <module>
    from mamba_ssm.ops.selective_scan_interface import selective_scan_fn, mamba_inner_fn
  File "/rds/general/user/kp4718/home/anaconda3/envs/mambaenv/lib/python3.10/site-packages/mamba_ssm/ops/selective_scan_interface.py", line 11, in <module>
    import selective_scan_cuda
ImportError: /rds/general/user/kp4718/home/anaconda3/envs/mambaenv/lib/python3.10/site-packages/selective_scan_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c107WarningC1ENS_7variantIJNS0_11UserWarningENS0_18DeprecationWarningEEEERKNS_14SourceLocationENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEb

**Comment by MarioPaps** [comment]
I was able to get around this problem [not sure if it is a proper solution] in Windows Subsystem for Linux:

1)Install cuda 11.8 driver from the link: https://developer.download.nvidia.com/compute/cuda/repos/wsl-ubuntu/x86_64/
2)Follow the installation instructions in the image:
![screenshot_nvidia](https://github.com/hustvl/Vim/assets/20114246/b49d95c8-abec-49ff-be99-2a7f2809af3a)
