### ISSUE TITLE
ImportError: libcudart.so.12: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Liuhp133** [hustvl/Vim#68]
Traceback (most recent call last):
  File "/home/omnisky/sdf/ljx/Vim/vim/main.py", line 28, in <module>
    import models_mamba
  File "/home/omnisky/sdf/ljx/Vim/vim/models_mamba.py", line 20, in <module>
    from mamba_ssm.modules.mamba_simple import Mamba
  File "/home/omnisky/sdf/ljx/Vim/mamba-1p1p1/mamba_ssm/__init__.py", line 3, in <module>
    from mamba_ssm.ops.selective_scan_interface import selective_scan_fn, mamba_inner_fn
  File "/home/omnisky/sdf/ljx/Vim/mamba-1p1p1/mamba_ssm/ops/selective_scan_interface.py", line 9, in <module>
    from causal_conv1d import causal_conv1d_fn
  File "/home/omnisky/anaconda3/envs/vim/lib/python3.10/site-packages/causal_conv1d/__init__.py", line 3, in <module>
    from causal_conv1d.causal_conv1d_interface import causal_conv1d_fn, causal_conv1d_update
  File "/home/omnisky/anaconda3/envs/vim/lib/python3.10/site-packages/causal_conv1d/causal_conv1d_interface.py", line 7, in <module>
    import causal_conv1d_cuda
ImportError: libcudart.so.12: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/omnisky/sdf/ljx/Vim/vim/main.py", line 28, in <module>
    import models_mamba
  File "/home/omnisky/sdf/ljx/Vim/vim/models_mamba.py", line 20, in <module>
    from mamba_ssm.modules.mamba_simple import Mamba
  File "/home/omnisky/sdf/ljx/Vim/mamba-1p1p1/mamba_ssm/__init__.py", line 3, in <module>
    from mamba_ssm.ops.selective_scan_interface import selective_scan_fn, mamba_inner_fn
  File "/home/omnisky/sdf/ljx/Vim/mamba-1p1p1/mamba_ssm/ops/selective_scan_interface.py", line 9, in <module>
    from causal_conv1d import causal_conv1d_fn
  File "/home/omnisky/anaconda3/envs/vim/lib/python3.10/site-packages/causal_conv1d/__init__.py", line 3, in <module>
    from causal_conv1d.causal_conv1d_interface import causal_conv1d_fn, causal_conv1d_update
  File "/home/omnisky/anaconda3/envs/vim/lib/python3.10/site-packages/causal_conv1d/causal_conv1d_interface.py", line 7, in <module>
    import causal_conv1d_cuda
ImportError: libcudart.so.12: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/omnisky/sdf/ljx/Vim/vim/main.py", line 28, in <module>
    import models_mamba
  File "/home/omnisky/sdf/ljx/Vim/vim/models_mamba.py", line 20, in <module>
    from mamba_ssm.modules.mamba_simple import Mamba
  File "/home/omnisky/sdf/ljx/Vim/mamba-1p1p1/mamba_ssm/__init__.py", line 3, in <module>
    from mamba_ssm.ops.selective_scan_interface import selective_scan_fn, mamba_inner_fn
  File "/home/omnisky/sdf/ljx/Vim/mamba-1p1p1/mamba_ssm/ops/selective_scan_interface.py", line 9, in <module>
    from causal_conv1d import causal_conv1d_fn
  File "/home/omnisky/anaconda3/envs/vim/lib/python3.10/site-packages/causal_conv1d/__init__.py", line 3, in <module>
    from causal_conv1d.causal_conv1d_interface import causal_conv1d_fn, causal_conv1d_update
  File "/home/omnisky/anaconda3/envs/vim/lib/python3.10/site-packages/causal_conv1d/causal_conv1d_interface.py", line 7, in <module>
    import causal_conv1d_cuda
ImportError: libcudart.so.12: cannot open shared object file: No such file or directory
[2024-04-19 14:55:55,003] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 13126) of binary: /home/omnisky/anaconda3/envs/vim/bin/python
Traceback (most recent call last):
  File "/home/omnisky/anaconda3/envs/vim/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/omnisky/anaconda3/envs/vim/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/omnisky/anaconda3/envs/vim/lib/python3.10/site-packages/torch/distributed/launch.py", line 196, in <module>
    main()
  File "/home/omnisky/anaconda3/envs/vim/lib/python3.10/site-packages/torch/distributed/launch.py", line 192, in main
    launch(args)
  File "/home/omnisky/anaconda3/envs/vim/lib/python3.10/site-packages/torch/distributed/launch.py", line 177, in launch
    run(args)
  File "/home/omnisky/anaconda3/envs/vim/lib/python3.10/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/home/omnisky/anaconda3/envs/vim/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/omnisky/anaconda3/envs/vim/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:

**Comment by zyszxhy** [comment]
Hello, have you solved this problem yet?
